version: "3"

services:

  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - parity
      - testrpc

  parity:
      image: "ethcore/parity:nightly"

  testrpc:
      image: "harshjv/testrpc"
