version: "3"

services:

  web:
    build: .
    ports:
      - "8081:8080"
    links:
      - parity

  parity:
      image: "ethcore/parity:nightly"
      ports:
        - "8080:8080"
        - "8545:8545"
